config/routes.rb
Rails.application.routes.draw do
  resources :residences
  resources :pictures, only: [:destroy], as: 'destroy_picture'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'listwithus' => 'pages#list_with_us'

  namespace 'search' do
    root to: :index
    get 'ajax', to: :ajax
  end

  get 'listing/:id' => 'listing#show', as: :listing

  root 'pages#home'

end

app/views/pages/home.html.haml
%header
	.overlay
	.social.hidden-xs
		%a{:href => "#"}
			%i.ion-social-twitter
		%a{:href => "#"}
			%i.ion-social-instagram
		%a{:href => "#"}
			%i.ion-social-facebook
	.container
		.row
			.col-md-8.col-md-offset-2.centered
				%h1
					= I18n.t('home.hero.title')
				%h3
					= I18n.t('home.hero.subtitle')
				%br/
				.form-group
					%form{action: "#{search_root_path}", method: "get"}
						.input-group.hero-form
							= text_field_tag :input, nil, class: "form-control", placeholder: I18n.t('home.hero.form.placeholder'), type: "text", id: "search_field"
							.input-group-btn
								%button{type: "submit", class: "btn btn-conf btn-green form-control"}
									= I18n.t('home.hero.form.button')

/ ********** GREY SECTION - BLOG **********
%section#grey
	.container
		.row
			.col-sm-12.text-center
				%h2
					= I18n.t('home.second_section.title')
				%br/
		.row
			%article.col-sm-6.col-md-4
				%a{:href => "#"}
					=image_tag "nacional.jpg", class: "img-responsive aligncenter"
					%h2
						= I18n.t('home.second_section.nacional')
			%article.col-sm-6.col-md-4
				%a{:href => "#"}
					=image_tag "javeriana.jpg", class: "img-responsive aligncenter"
					%h2
						= I18n.t('home.second_section.javeriana')
			%article.col-sm-6.col-md-4
				%a{:href => "#"}
					=image_tag "andes.jpg", class: "img-responsive aligncenter"
					%h2
						= I18n.t('home.second_section.andes')

/ ********** GREY SECTION **********
%footer
	.container
		.row
			.col-xs-12.col-md-offset-2.col-md-4
				%h5
					= I18n.t('home.footer.first_section.title')
				%hr/
				%p
					=I18n.t('home.footer.first_section.content_1')
					%br>/
					=I18n.t('home.footer.first_section.content_2')
			.col-xs-12.col-md-offset-1.col-md-4
				%h5
					=I18n.t('home.footer.social_section.title')
				%hr/
				%p
					=I18n.t('home.footer.social_section.content')
				%p
					%a{:href => "www.facebook.com/campushouse"}
						%i.fa.fa-facebook-official.fa-2x

app/views/pages/list_with_us.html.haml
.container
	.title
		%h2 Arrienda cupos a estudiantes
	%hr/
	%br/
	.row
		.col-xs-12.col-sm-4
			.icon
				%i.fa.fa-graduation-cap{:style => "font-size:64px;color:#03C9A9"}
			%h3 Encuentra estudiantes
			%p Muchos estudiantes se conectan a Campus House para encontrar una residencia cerca a su universidad.
		.col-xs-12.col-sm-4
			.icon
				%i.fa.fa-envelope{:style => "font-size:64px;color:#03C9A9"}
			%h3 Recibe ofertas
			%p Agenda citas y recibe ofertas directamente en tu correo electrónico.
		.col-xs-12.col-sm-4
			.icon
				%i.fa.fa-tablet{:style => "font-size:64px;color:#03C9A9"}
			%h3 Administra fácilmente
			%p Administra listados desde tu computador, tablet o teléfono móvil.
	%br/
	.subtitle
		Publica con nosotros gratis
	%br/
	.button= link_to "Publicar residencia", residences_path, require_login: true, class: 'btn btn-lg btn-green'