config/routes.rb
Rails.application.routes.draw do
  resources :residences
  resources :pictures, only: [:destroy], as: 'destroy_picture'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'listwithus' => 'pages#list_with_us'

  namespace 'search' do
    root to: :index
    get 'ajax', to: :ajax
  end

  get 'listing/:id' => 'listing#show', as: :listing

  root 'pages#home'

end

app/models/residence.rb
# == Schema Information
#
# Table name: residences
#
#  id            :integer          not null, primary key
#  name          :string
#  address       :string           not null
#  price         :decimal(7, )     not null
#  square_meters :integer
#  description   :text
#  rooms         :integer
#  user_id       :integer
#  archived      :boolean          default(FALSE)
#  latitude      :float
#  longitude     :float
#  city_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Residence < ActiveRecord::Base

	belongs_to :user, inverse_of: :published_residences
	
  has_many :pictures, inverse_of: :residence, dependent: :destroy
  accepts_nested_attributes_for :pictures, allow_destroy: true

	has_many :ratings
  belongs_to :city, inverse_of: :residences

	# List of features of this residence
	has_many :residence_features
	has_many :features, through: :residence_features

	# Students who faved this residence
	has_many :favs
	has_many :students_who_faved, through: :favs, class_name: 'User'

  validates :name, length: { maximum: 32 }, presence: true
  validates :address, length: { maximum: 64 }, presence: true
  validates :price, numericality: {
    greater_than_or_equal_to: 100_000,
    less_than_or_equal_to: 5_000_000
  }, presence: true
  validates :square_meters, numericality: {
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 300
  }, allow_nil: true
  validates :description, length: { maximum: 1000 }, presence: true
  validates :rooms, numericality: {
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 100
  }, allow_nil: true
  validates :city, presence: true

  geocoded_by :address

  after_validation :geocode, if: ->{ Rails.env.production? }
  before_validation :format_address

  scope :active, ->{ where(archived: false) }

  def archive
    self.update(archived: true)
  end

  private

  # attach the name of the city to be correctly geocoded
  def format_address
    self.address = "#{address}, #{city.name}" unless address.nil? || city.nil?
  end

end

app/controllers/residences_controller.rb
class ResidencesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_residence, only: [:show, :edit, :update, :destroy]
  before_action :verify_residence_ownership, only: [:show, :edit, :update, :destroy]
  before_action :verify_if_archived, only: [:show, :edit, :update]

  # GET /residences
  # GET /residences.json
  def index
    current_user.update(owner_enabled: true)
    @residences = current_user.published_residences.active
  end

  # GET /residences/1
  # GET /residences/1.json
  def show
    @pictures = @residence.pictures.all
  end

  # GET /residences/new
  def new
    @residence = Residence.new
    @pictures = @residence.pictures.build
  end

  # GET /residences/1/edit
  def edit
    @actual_pictures = @residence.pictures
  end

  # POST /residences
  # POST /residences.json
  def create
    # byebug
    @residence = Residence.new(residence_params)
    @residence.user = current_user

    build_pictures(params)
    
    respond_to do |format|
      if @residence.save
        format.html { redirect_to @residence, notice: 'Residence was successfully created.' }
        format.json { render :show, status: :created, location: @residence }
      else
        format.html { render :new, residence: @residence }
        format.json { render json: @residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residences/1
  # PATCH/PUT /residences/1.json
  def update
    build_pictures(params)

    respond_to do |format|
      if @residence.update(residence_params)
        format.html { redirect_to @residence, notice: 'Residence was successfully updated.' }
        format.json { render :show, status: :ok, location: @residence }
      else
        format.html { render :edit }
        format.json { render json: @residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residences/1
  # DELETE /residences/1.json
  def destroy
    @residence.archive
    respond_to do |format|
      format.html { redirect_to residences_url, notice: 'Residence was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_residence
      @residence = Residence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def residence_params
      params.require(:residence).permit(
        :name,
        :address,
        :price,
        :square_meters,
        :city_id,
        :description,
        :rooms,
        pictures_attributes: [:picture]
      )
    end

    def verify_residence_ownership
      redirect_to residences_path unless @residence.user == current_user
    end

    def verify_if_archived
      redirect_to residences_path if @residence.archived?
    end

    def build_pictures(params)
      unless params[:pictures].nil?
        params[:pictures]['picture'].each do |picture|
           @pictures = @residence.pictures.build(picture: picture)
        end
      end
    end
end

app/helpers/residences_helper.rb
module ResidencesHelper
end

app/views/residences/_form.html.haml
= form_for @residence, html: { multipart: true } do |f|
  - if @residence.errors.any?
    #error_explanation
      %ul
        - @residence.errors.messages.each do |msg|
          - msg.last.each do |m|
            %li= m
  .field
    = f.label :name, I18n.t('activerecord.fields.residence.name')
    = f.text_field :name
  .field
    = f.label :city_id, I18n.t('activerecord.fields.residence.city')
    = f.collection_select(:city_id, City.all, :id, :name)
  .field
    = f.label :address, I18n.t('activerecord.fields.residence.address')
    = f.text_field :address
  .field
    = f.label :price, I18n.t('activerecord.fields.residence.price')
    = f.text_field :price
  .field
    = f.label :square_meters, I18n.t('activerecord.fields.residence.square_meters')
    = f.number_field :square_meters
  .field
    = f.label :description, I18n.t('activerecord.fields.residence.description')
    = f.text_area :description
  .field
    = f.label :rooms, I18n.t('activerecord.fields.residence.rooms')
    = f.number_field :rooms

  - if action_name == 'edit'
    - @actual_pictures.each do |actual_picture|
      .picture-container
        = image_tag actual_picture.picture.thumb
        %p= link_to 'Destroy', destroy_picture_path(actual_picture), class: 'delete-picture-link', method: :delete, data: { :confirm => 'Are you sure?' }, remote: true

  = f.fields_for :pictures, @residence.pictures.new do |builder|
    .field
      = builder.label :picture, I18n.t('activerecord.fields.residence.images')
      %br/
      = builder.file_field :picture, multiple: true, name: "pictures[picture][]"

  .actions
    = f.submit 'Guardar'

app/views/residences/edit.html.haml
%h1 Editing residence

= render 'form'

= link_to 'Show', @residence
\|
= link_to 'Back', residences_path

app/views/residences/index.html.haml
%h1 Listing residences

%table
  %thead
    %tr
      %th Name
      %th Address
      %th Price
      %th Square meters
      %th Description
      %th Rooms
      %th
      %th
      %th

  %tbody
    - @residences.each do |residence|
      %tr
        %td= residence.name
        %td= residence.address
        %td= residence.price
        %td= residence.square_meters
        %td= residence.description
        %td= residence.rooms
        %td= link_to 'Show', residence
        %td= link_to 'Edit', edit_residence_path(residence)
        %td= link_to 'Destroy', residence, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Residence', new_residence_path

app/views/residences/new.html.haml
%h1 New residence

= render 'form'

= link_to 'Back', residences_path

app/views/residences/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @residence.name
%p
  %b Address:
  = @residence.address
%p
  %b Price:
  = @residence.price
%p
  %b Square meters:
  = @residence.square_meters
%p
  %b Description:
  = @residence.description
%p
  %b Rooms:
  = @residence.rooms
- @pictures.each do |picture|
  .picture-container
    = image_tag picture.picture.thumb
    %p= link_to 'Destroy', destroy_picture_path(picture), class: 'delete-picture-link', method: :delete, data: { :confirm => 'Are you sure?' }, remote: true

= link_to 'Edit', edit_residence_path(@residence)
\|
= link_to 'Back', residences_path