config/routes.rb
Rails.application.routes.draw do
  resources :residences
  resources :pictures, only: [:destroy], as: 'destroy_picture'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'listwithus' => 'pages#list_with_us'

  namespace 'search' do
    root to: :index
    get 'ajax', to: :ajax
  end

  get 'listing/:id' => 'listing#show', as: :listing

  root 'pages#home'

end

app/views/layouts/_alert.html.haml
%div{:class => "alert alert-#{status}", :role => "alert"}
	= notice

app/views/layouts/_student_navbar.html.haml
- if current_user.owner_enabled?
	%li
		= link_to "Residencias publicadas", '#'
%li
	= link_to "Tus favoritos ❤", '#'
%li.dropdown
	%a{href: "#", class: 'dropdown-toggle', 'data-toggle' => 'dropdown', role: 'button', 'aria-haspopup' => 'true', 'aria-expanded' => "false"}
		= current_user.name
		%span.caret
	%ul.dropdown-menu
		%li
			= link_to "Cerrar sesión", destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html{lang: I18n.locale.to_s}
	%head
		%meta{"http-equiv" => "Content-Type"}/
		%meta{charset: "UTF-8"}/
		%meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
		%title Residences
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places'
		= csrf_meta_tags
		= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css'
	%body{:class => "#{controller_name} #{action_name}"}
		.alert-wrap
			- if notice
				= render partial: "layouts/alert", locals: {status: "success", notice: notice}
			- if alert
				= render partial: "layouts/alert", locals: {status: "warning", notice: alert}
		%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
			.container-fluid
				.navbar-header
					%a.navbar-brand{:href => root_path} CAMPUS HOUSE
					- if false # Show search bar in navbar in future versions
					- # if "#{controller_name}-#{action_name}" != 'pages-home'
						%form.navbar-form.navbar-left{:role => "search"}
							.input-group
								%span.input-group-addon
									%i.fa.fa-search
								%input.form-control{:placeholder => "¿Dónde estás buscando?", :type => "text"}
				.collapse.navbar-collapse
					%ul.nav.navbar-nav.navbar-right
						- if controller_name == 'pages' && !current_user.try(:owner_enabled?)
							%li.bordered-item
								%div
									= link_to "Publica con nosotros", listwithus_path
						- if user_signed_in?
							= render('layouts/student_navbar')
						- else
							%li
								= link_to "Regístrate", '#', 'data-toggle' => "modal", 'data-target' => '#RegisterModal'
							%li
								= link_to "Iniciar sesión", '#', 'data-toggle' => "modal", 'data-target' => '#SignInModal'
		= yield
		= render 'devise/sessions/new'
		= render 'devise/registrations/new'